# Generated by Django 6.0.4 on 2026-05-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("decoupage_administratif", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="epci",
            options={"verbose_name": "EPCI", "verbose_name_plural": "EPCIs"},
        ),
        migrations.AlterModelOptions(
            name="region",
            options={"verbose_name": "region", "verbose_name_plural": "regions"},
        ),
        migrations.AlterField(
            model_name="city",
            name="population",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
