# Generated by Django 6.0.5 on 2026-05-18 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("decoupage_administratif", "0002_alter_epci_options_alter_region_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="epci",
            options={"verbose_name": "EPCI", "verbose_name_plural": "EPCI"},
        ),
        migrations.AlterModelOptions(
            name="region",
            options={"verbose_name": "région", "verbose_name_plural": "régions"},
        ),
        migrations.RemoveIndex(
            model_name="city",
            name="da_city_name_trgm_idx",
        ),
        migrations.RemoveIndex(
            model_name="department",
            name="da_dept_name_trgm_idx",
        ),
        migrations.RemoveIndex(
            model_name="epci",
            name="da_epci_name_trgm_idx",
        ),
        migrations.RemoveIndex(
            model_name="region",
            name="da_region_name_trgm_idx",
        ),
        migrations.RemoveField(
            model_name="city",
            name="center",
        ),
        migrations.RemoveField(
            model_name="city",
            name="epci",
        ),
        migrations.RemoveField(
            model_name="city",
            name="normalized_name",
        ),
        migrations.RemoveField(
            model_name="city",
            name="population",
        ),
        migrations.RemoveField(
            model_name="city",
            name="postal_codes",
        ),
        migrations.RemoveField(
            model_name="city",
            name="region",
        ),
        migrations.RemoveField(
            model_name="department",
            name="normalized_name",
        ),
        migrations.RemoveField(
            model_name="epci",
            name="departments",
        ),
        migrations.RemoveField(
            model_name="epci",
            name="normalized_name",
        ),
        migrations.RemoveField(
            model_name="epci",
            name="regions",
        ),
        migrations.RemoveField(
            model_name="region",
            name="normalized_name",
        ),
    ]
