# Generated by Django 6.0.1 on 2026-01-28 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import itoutils.django.nexus.models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0002_item_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncedItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField()),
                ("sync_me", models.BooleanField(default=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(itoutils.django.nexus.models.NexusModelMixin, models.Model),
        ),
    ]
