# Generated by Django 6.0.1 on 2026-01-27 12:54

import django.db.models.deletion
from django.db import migrations, models

import itoutils.django.nexus.models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0002_item_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncedItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField()),
                ("sync_me", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="testapp.synceditem",
                    ),
                ),
            ],
            bases=(itoutils.django.nexus.models.NexusModelMixin, models.Model),
        ),
    ]
